use axfetchum::{GeneratorConfig, api_routes, generate};

fn yauth_config() -> GeneratorConfig {
    GeneratorConfig {
        bindings_dir: "./bindings".into(),
        output_path: "./packages/client/src/generated.ts".into(),
        factory_name: "createYAuthClient".into(),
        enable_groups: true,
        error_class_name: "YAuthError".into(),
        options_interface_name: "YAuthClientOptions".into(),
        default_credentials: "include".into(),
        type_import_prefix: "../../../../bindings".into(),
        format_command: None,
    }
}

fn sample_routes() -> axfetchum::RouteCollection {
    let mut routes = api_routes! {
        getSession: GET "/session" [auth]
            -> SessionResponse;
        logout: POST "/logout" [auth]
            -> SuccessResponse;
        updateProfile: PATCH "/me" [auth]
            body: UpdateProfileRequest -> ProfileResponse;
    };

    let ep = api_routes! {
        @group emailPassword

        register: POST "/register"
            body: RegisterRequest -> MessageResponse;
        login: POST "/login"
            body: LoginRequest -> LoginResponse;
        verify: POST "/verify-email"
            body: VerifyEmailRequest -> MessageResponse;
        changePassword: POST "/change-password" [auth]
            body: ChangePasswordRequest -> MessageResponse;
    };
    routes.extend(ep);

    let admin = api_routes! {
        @group admin

        listUsers: GET "/admin/users" [auth]
            query: ListUsersQuery -> ListUsersResponse;
        getUser: GET "/admin/users/{id}" [auth]
            -> UserResponse;
        deleteUser: DELETE "/admin/users/{id}" [auth];
        banUser: POST "/admin/users/{id}/ban" [auth]
            body: BanRequest -> UserResponse;
    };
    routes.extend(admin);

    let oauth = api_routes! {
        @group oauth

        authorize: GET "/oauth/{provider}/authorize" [redirect]
            query: AuthorizeQuery;
        callback: POST "/oauth/{provider}/callback"
            body: CallbackBody -> AuthResponse;
    };
    routes.extend(oauth);

    routes
}

#[test]
fn generates_valid_output() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Header
    assert!(output.starts_with("// Auto-generated by axfetchum. Do not edit.\n"));

    // Imports exist for custom types
    assert!(output.contains("import type { RegisterRequest }"));
    assert!(output.contains("import type { LoginResponse }"));
    assert!(output.contains("import type { ListUsersQuery }"));
    assert!(output.contains("import type { UserResponse }"));
    assert!(output.contains("import type { AuthorizeQuery }"));

    // Error class
    assert!(output.contains("export class YAuthError extends Error"));

    // Options interface
    assert!(output.contains("export interface YAuthClientOptions"));

    // Factory function
    assert!(output.contains("export function createYAuthClient(options: YAuthClientOptions)"));

    // Type export
    assert!(output.contains("export type YAuthClient = ReturnType<typeof createYAuthClient>;"));
}

#[test]
fn generates_ungrouped_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Top-level routes (not in a group)
    assert!(output.contains("getSession: () => request<SessionResponse>(\"/session\""));
    assert!(output.contains("logout: () => request<SuccessResponse>(\"/logout\""));
}

#[test]
fn generates_grouped_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Group structure
    assert!(output.contains("emailPassword: {"));
    assert!(output.contains("admin: {"));
    assert!(output.contains("oauth: {"));

    // Group methods
    assert!(output.contains("register: (body: RegisterRequest)"));
    assert!(output.contains("login: (body: LoginRequest)"));
}

#[test]
fn generates_path_params() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Path params become function args and template literals
    assert!(output.contains("getUser: (id: string)"));
    assert!(output.contains("`/admin/users/${id}`"));
    assert!(output.contains("banUser: (id: string, body: BanRequest)"));
}

#[test]
fn generates_query_params() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Query params
    assert!(output.contains("listUsers: (query?: ListUsersQuery)"));
    assert!(output.contains("query"));
}

#[test]
fn generates_redirect_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Redirect routes generate URL builders, not fetch calls
    assert!(output.contains("authorize:"));
    assert!(output.contains("options.baseUrl"));
    // Should NOT contain request<...> for redirect routes
    let authorize_section = output
        .split("authorize:")
        .nth(1)
        .unwrap()
        .split('}')
        .next()
        .unwrap();
    assert!(!authorize_section.contains("request<"));
}

#[test]
fn generates_auth_flag() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Auth routes have auth: true in options
    assert!(output.contains("auth: true"));
}

#[test]
fn generates_void_return_for_no_response() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // deleteUser has no response type (8 spaces indent: 6 base + 2 continuation)
    assert!(output.contains("deleteUser: (id: string) =>\n        request<void>"));
}

#[test]
fn generates_request_helper() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Request helper should contain error handling
    assert!(output.contains("function createRequest(options: YAuthClientOptions)"));
    assert!(output.contains("new YAuthError("));
    assert!(output.contains("credentials"));
    assert!(output.contains("getToken"));
}

#[test]
fn flat_mode_no_groups() {
    let routes = sample_routes();
    let config = GeneratorConfig {
        enable_groups: false,
        ..yauth_config()
    };
    let output = generate(&routes, &config);

    // Should not have group objects
    assert!(!output.contains("emailPassword: {"));
    assert!(!output.contains("admin: {"));
    // All routes at top level
    assert!(output.contains("register:"));
    assert!(output.contains("listUsers:"));
}

#[test]
fn check_detects_out_of_sync() {
    use std::io::Write;

    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axfetchum_test");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        ..yauth_config()
    };

    // Write wrong content
    let mut f = std::fs::File::create(&output_path).unwrap();
    writeln!(f, "// old content").unwrap();
    drop(f);

    // Check should fail
    let result = axfetchum::check(&routes, &config);
    assert!(result.is_err());

    // Now write correct content
    axfetchum::generate_to_file(&routes, &config).unwrap();

    // Check should pass
    let result = axfetchum::check(&routes, &config);
    assert!(result.is_ok());

    // Cleanup
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn snapshot_yauth_style_output() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Write snapshot for manual inspection
    let snapshot_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/snapshots/yauth_style.ts"
    );
    std::fs::write(snapshot_path, &output).unwrap();

    // Verify it can be re-read and matches
    let re_read = std::fs::read_to_string(snapshot_path).unwrap();
    assert_eq!(output, re_read);
}

#[test]
fn generate_to_file_runs_format_command() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axfetchum_fmt_test");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    // Use sed to replace a known string, proving the formatter ran
    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };

    axfetchum::generate_to_file(&routes, &config).unwrap();

    let content = std::fs::read_to_string(&output_path).unwrap();
    assert!(
        content.contains("FORMATTED"),
        "format command should have replaced 'Auto-generated' with 'FORMATTED'"
    );
    assert!(
        !content.contains("Auto-generated"),
        "original text should have been replaced"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn check_passes_with_format_command() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axfetchum_fmt_check");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };

    // generate_to_file writes + formats
    axfetchum::generate_to_file(&routes, &config).unwrap();

    // check should pass (generates to temp, formats, compares)
    let result = axfetchum::check(&routes, &config);
    assert!(
        result.is_ok(),
        "check should pass after generate_to_file with same format_command"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn check_fails_when_format_command_not_applied() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axfetchum_fmt_mismatch");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    // Write unformatted output
    let unformatted_config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: None,
        ..yauth_config()
    };
    axfetchum::generate_to_file(&routes, &unformatted_config).unwrap();

    // Check with a format_command — the on-disk file is unformatted, so it should fail
    let formatted_config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };
    let result = axfetchum::check(&routes, &formatted_config);
    assert!(
        result.is_err(),
        "check should fail when on-disk file was not formatted"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn format_command_none_preserves_existing_behavior() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axfetchum_no_fmt");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: None,
        ..yauth_config()
    };

    axfetchum::generate_to_file(&routes, &config).unwrap();

    // Content should match raw generate() output exactly
    let content = std::fs::read_to_string(&output_path).unwrap();
    let expected = generate(&routes, &config);
    assert_eq!(content, expected);

    // check should pass
    let result = axfetchum::check(&routes, &config);
    assert!(result.is_ok());

    std::fs::remove_dir_all(&dir).ok();
}
