// Auto-generated by axfetchum. Do not edit.

import type { AuthResponse } from "../../../../bindings/AuthResponse";
import type { AuthorizeQuery } from "../../../../bindings/AuthorizeQuery";
import type { BanRequest } from "../../../../bindings/BanRequest";
import type { CallbackBody } from "../../../../bindings/CallbackBody";
import type { ChangePasswordRequest } from "../../../../bindings/ChangePasswordRequest";
import type { ListUsersQuery } from "../../../../bindings/ListUsersQuery";
import type { ListUsersResponse } from "../../../../bindings/ListUsersResponse";
import type { LoginRequest } from "../../../../bindings/LoginRequest";
import type { LoginResponse } from "../../../../bindings/LoginResponse";
import type { MessageResponse } from "../../../../bindings/MessageResponse";
import type { ProfileResponse } from "../../../../bindings/ProfileResponse";
import type { RegisterRequest } from "../../../../bindings/RegisterRequest";
import type { SessionResponse } from "../../../../bindings/SessionResponse";
import type { SuccessResponse } from "../../../../bindings/SuccessResponse";
import type { UpdateProfileRequest } from "../../../../bindings/UpdateProfileRequest";
import type { UserResponse } from "../../../../bindings/UserResponse";
import type { VerifyEmailRequest } from "../../../../bindings/VerifyEmailRequest";

export class YAuthError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);
    this.name = "YAuthError";
  }
}

export interface YAuthClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: YAuthError) => void;
}

type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
};

function createRequest(options: YAuthClientOptions) {
  const { baseUrl, credentials = "include" } = options;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const { method = "GET", body, query, auth } = opts;
    // Resolve fetch at call time (not at client creation) so OTel
    // instrumentation patches are picked up even when the client
    // module is imported before telemetry initializes.
    const fetchFn = options.fetch ?? globalThis.fetch;

    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          params.set(key, String(value));
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" };

    if (auth && options.getToken) {
      const token = await options.getToken();
      if (token) headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchFn(url, {
      method,
      credentials,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new YAuthError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export function createYAuthClient(options: YAuthClientOptions) {
  const request = createRequest(options);

  return {
    getSession: () => request<SessionResponse>("/session", { auth: true }),
    logout: () => request<SuccessResponse>("/logout", { method: "POST", auth: true }),
    updateProfile: (body: UpdateProfileRequest) =>
      request<ProfileResponse>("/me", { method: "PATCH", auth: true, body }),

    admin: {
      listUsers: (query?: ListUsersQuery) =>
        request<ListUsersResponse>("/admin/users", { auth: true, query }),
      getUser: (id: string) =>
        request<UserResponse>(`/admin/users/${id}`, { auth: true }),
      deleteUser: (id: string) =>
        request<void>(`/admin/users/${id}`, { method: "DELETE", auth: true }),
      banUser: (id: string, body: BanRequest) =>
        request<UserResponse>(`/admin/users/${id}/ban`, { method: "POST", auth: true, body }),
    },

    emailPassword: {
      register: (body: RegisterRequest) =>
        request<MessageResponse>("/register", { method: "POST", body }),
      login: (body: LoginRequest) =>
        request<LoginResponse>("/login", { method: "POST", body }),
      verify: (body: VerifyEmailRequest) =>
        request<MessageResponse>("/verify-email", { method: "POST", body }),
      changePassword: (body: ChangePasswordRequest) =>
        request<MessageResponse>("/change-password", { method: "POST", auth: true, body }),
    },

    oauth: {
      authorize: (provider: string, query?: AuthorizeQuery) => {
        let url = `${options.baseUrl}/oauth/${provider}/authorize`;
        if (query) {
          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(query)) {
            if (value !== undefined && value !== null) params.set(key, String(value));
          }
          const qs = params.toString();
          if (qs) url += `?${qs}`;
        }
        return url;
      },
      callback: (provider: string, body: CallbackBody) =>
        request<AuthResponse>(`/oauth/${provider}/callback`, { method: "POST", body }),
    },
  };
}

export type YAuthClient = ReturnType<typeof createYAuthClient>;
